apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vks-02-gitops
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.6.0
    classNamespace: vmware-system-vks-public
    version: v1.34.2---vmware.2-vkr.2
    variables:
      - name: kubernetes
        value:
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vsan-default-storage-policy
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-03a37b547e2e41e3e
    workers:
      machineDeployments:
        - class: node-pool
          name: vks-01-gitops-np-s2ih
          replicas: 2
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-03a37b547e2e41e3e
          variables:
            overrides:
              - name: node
                value:
                  labels:
                    provisioned-by: argocd
