apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: guestbook-appset-listgen
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list: 
      # The template below uses these parameters
      elements: 
      - cluster: vks-04-gitops
        url: https://10.1.11.4:6443
      - cluster: vks-01-gitops
        url: https://10.1.11.2:6443
  template: 
    # inserts cluster and url values from parameters defined above
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/tkrausjr/vcf-argocd-gitops.git
        targetRevision: HEAD
        path: guestbook-app/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: default
      syncPolicy:
        automated:
          enabled: true          
          selfHeal: true