apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: two-tier-vm-mysql
  namespace: test-ns01
  labels:
    vm-selector: two-tier-vm-mysql
    topology.kubernetes.io/zone: z-wld-a  # In vSphere NAmespace kubectl get zone
spec:
  className: best-effort-small
  imageName: vmi-0789eef444d057340
  storageClass: nfs-datastore-policy
  powerState: PoweredOn
  volumes:
    - name: vcf-edge-sample-ubuntu-vm-pvc-0
      persistentVolumeClaim:
        claimName: vcf-edge-sample-ubuntu-vm-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcf-edge-sample-ubuntu-vm-pvc-0
  namespace: test-ns01
  labels:
    vm-selector: two-tier-vm-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-datastore-policy
