apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: gitops-ubuntu-vm
  namespace: demo-org-apps-kjl82
  labels:
    vm-selector: gitops-ubuntu-vm
    topology.kubernetes.io/zone: domain-c10
spec:
  className: best-effort-small
  imageName: vmi-f0e634cb6faede95e
  storageClass: vsan-default-storage-policy
  powerState: PoweredOn
  volumes:
    - name: vcf-edge-sample-ubuntu-vm-pvc-0
      persistentVolumeClaim:
        claimName: vcf-edge-sample-ubuntu-vm-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcf-edge-sample-ubuntu-vm-pvc-0
  namespace: demo-org-apps-kjl82
  labels:
    vm-selector: gitops-ubuntu-vm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: vsan-default-storage-policy
