apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-tier-mysql
  namespace: shared-svcs-hycxp
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: multi-tier/apps/mysql-vm-app
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc.cluster.local:443'
    namespace: shared-svcs-hycxp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
