apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vks-02-cluster-test-ns01
  namespace: shared-svcs 
spec:
  project:
  source:
    repoURL: https://github.com/tkrausjr/vcf-argocd-gitops.git
    path: vks-cluster/k8s
    targetRevision: HEAD
  destination:
    server: https://10.1.0.6:443
    namespace: test-ns01
  syncPolicy:
   automated: {}